server:
  port: 8081

spring:
  application:
    name: file-storing-service
  datasource:
    url: jdbc:postgresql://postgres:5432/textscanner_files
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          provider_disables_autocommit: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    use-root-path: true
  packages-to-scan: com.textscanner.filestore.controller
  group-configs:
    - group: storage
      paths-to-match: /api/files/** 